apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-jifelog-com

resources:
  - ../../base

images:
  - name: jifelog-feed-api
    newName: jhjun07/jifelog-feed-api
    newTag: dev-280d2f0f92c9ee3803e8377193ef65ea80ec54f8

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml