apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-jifelog-com

resources:
  - ../../base

images:
  - name: jifelog-feed-api
    newName: jhjun07/jifelog-feed-api
    newTag: dev-6ab86587a144d33e015189c16d14c511d4fcff7a

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml